# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50cc38a9b3812ffa692241582db7b5589f4652f9cc02bfdd108b5f2698915fab74b4c91b7bb284c428d718d1a2dc81f0e467ebd53f5b059f5940e735e8313de

test:
  secret_key_base: 18315188167db873002b8e1026747ad3226ccb99528c58e033b62f0b106626963e8f92a77aef0daf0e09ff91d31d4d0ec1da3a23bff3e9da328364b4495859b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
